/* ============================================================================
   サンライズ 様 商品データ登録スクリプト（MySQL）

   対象   : `ExcutionBudget`.`RDS_PRD` または `ExcutionBudget`.`RDS_TEST`
            （下の「設定」の @target_table で切り替える）
   元資料 : サンライズ様商品登録20260914.xlsx（Sheet1）
   件数   : 985 件

   ---------------------------------------------------------------------------
   ★ Excel 列 → テーブル列の対応 ★

     A メーカー名          → manufacturer
     B 品名-product_name   → product_name
     C 品番-productnumber  → productnumber   ※ Excel では色名が入力されている
     D 色-color            → color           ※ Excel では全行空欄のため NULL
     E 入数-quantity       → quantity
     F 単位-case_unit      → case_unit
     G 定尺                → length          ※ 全行空欄のため NULL
     H 価格                → standard_price  ※ 全行空欄のため 0
     （Excel に無い列）    → case, quantity_unit は NULL

   ---------------------------------------------------------------------------
   ★ 仕組み ★

     MySQL はテーブル名に変数を直接使えないため、次の手順で登録する。

       1. 登録先と同じ構成の一時テーブル `ExcutionBudget`.`tmp_import_sunrise` を作り、
          全データをそこへ INSERT する（一時テーブル名は固定なので変数不要）
       2. 一時テーブル → @target_table へ INSERT ... SELECT する
          （この文だけ変数から組み立てて PREPARE / EXECUTE で実行）

     一時テーブルは接続（セッション）を切ると自動で消える。
     変数（@target_table など）も接続ごとに消えるため、接続し直した場合は
     「設定」から実行し直すこと。

   ★ id ★

     INSERT では id を指定しない（登録先の AUTO_INCREMENT で採番される）。

   進め方 : 設定 → STEP 0 → 1 → 2 → 3 → 4 → COMMIT → 5 の順に、
            各ブロックを選択して実行する。
   ============================================================================ */


/* ============================================================================
   設定 : ★ 登録先はここだけ変更する ★
   ---------------------------------------------------------------------------
   'RDS_TEST' または 'RDS_PRD'
   ============================================================================ */
SET @target_table = 'RDS_TEST';

SET @manufacturer = 'サンライズ';   -- 変更不要


/* ============================================================================
   STEP 0 : 開いているトランザクションを閉じる（毎回最初に実行）
   ============================================================================ */
ROLLBACK;

SELECT @target_table AS target_table;   -- 登録先が正しいか必ず目視確認する


/* ============================================================================
   STEP 1 : 登録済みでないか確認する
   ---------------------------------------------------------------------------
   → 0 件なら STEP 2 へ
   → 件数が出たら既に登録済み。二重登録になるため中止して確認する
   ============================================================================ */
SET @sql = CONCAT('SELECT COUNT(*) AS registered_rows FROM `ExcutionBudget`.`', @target_table,
                  '` WHERE `manufacturer` = ?');
PREPARE stmt FROM @sql;
EXECUTE stmt USING @manufacturer;
DEALLOCATE PREPARE stmt;


/* ============================================================================
   STEP 2 : 一時テーブルを作り、全データを入れる
   ============================================================================ */
DROP TEMPORARY TABLE IF EXISTS `ExcutionBudget`.`tmp_import_sunrise`;

SET @sql = CONCAT('CREATE TEMPORARY TABLE `ExcutionBudget`.`tmp_import_sunrise` LIKE `ExcutionBudget`.`', @target_table, '`');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 1 ～ 100 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'シロ', 'NB５０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シロ', 'NB５０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ライトグレー', 'NB５０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ライトグレー', 'NB５０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ASSブルー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ASSブルー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ASクリーム', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Cライトグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Cライトグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Dクリーム', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Dクリーム', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Fイエロー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Fイエロー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Fブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Fブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Fブルー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Fホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Fホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Jオーカー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Jオーカー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Jグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Jグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Kオーカー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Kオーカー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Kモザイクグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Kモザイクグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'LDベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'LDベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Nクリーム', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Nクリーム', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Nセピア', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Nセピア', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Nダークブルー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Nダークブルー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Nホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Nホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Pチタングレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Pチタングレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'SMブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'SMブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'SPAブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'SPAブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'SPフォーンBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'SPフォーンBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'SSブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'SSブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'SカスタードBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'SカスタードBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Sチタンベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Sベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Sベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tアーバングレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tアーバングレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TアイボリーDT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TアイボリーDT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TアイボリーEF', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TアイボリーEF', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TアスールO', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TアスールO', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TアッシュO', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tアルモブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tアルモブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TアンティークB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TアンティークB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TイエローDT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TイエローDT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TイエローSDT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TイエローSDT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tウグイスチャ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tウグイスチャ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tウチコングレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TエスペリオW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TエスペリオW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TオレンジK', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TオレンジK', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TオレンジSDT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TオレンジSDT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TカジュアルＡ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TカジュアルＡ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tカロスミント', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tカロスミント', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TカンザスDB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TカンザスDB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TカンザスW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TカンザスW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TキールO', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TキールO', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TキールS', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TキールS', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TクラウンＡ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TクラウンＡ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TクラシックBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TクラシックBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TグリーンＧDT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TグリーンＧDT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TグレーK', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TグレーK', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TグレーPM', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TグレーPM', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tクレマベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL);

-- 101 ～ 200 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'Tクレマベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tコールブラック', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tコールブラック', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TシェールS', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TシャギーＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TステインB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TステインB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tセラベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tセラベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TソフトDT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TソフトDT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tソルアイボリー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tソルアイボリー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tダークグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tダークグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TチャコールBK', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TチャコールBK', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TティーフC', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TティーフC', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tテンダーブルー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tテンダーブルー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TネビアB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TネビアB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TネビアＧ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TネビアＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TパーチェF', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TパーチェF', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tパーチェカフェ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tパーチェカフェ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TハウッドS', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TハウッドS', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TヒウチY', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TヒウチY', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TビュアC', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TビュアC', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TファータF', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TファータF', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TファータK', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TファータK', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tファータバニラ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tファータバニラ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TフェアリーＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TフォーンBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tフォンセワイン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tフォンセワイン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンDT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンDT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンEF', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンEF', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンK', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンK', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンKC', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンKC', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TブリックK', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TブリックK', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TフロストW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TフロストW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tベンガラ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tベンガラ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトDT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトDT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトEF', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトEF', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトSC', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトSC', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトV', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトV', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトY', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TモクメW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TモクメW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TモクメY', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオBＧ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオBＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオOR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオOR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TリベルピュアW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TリベルピュアW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tルーツホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tルーツホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tルーツミスト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tルーツミスト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TルーラルB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TルーラルB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tルナホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tルナホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TレジェC', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TレジェC', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TレトロPC', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TレトロPC', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Yアイボリー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Yスパニッシュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Yスパニッシュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Yマホガニー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アースブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アースブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アーバンブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL);

-- 201 ～ 300 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'アーバンブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アイアンブラック', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アイアンブラック', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アイイロ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アイイロ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アイボリー２', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アイボリーW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アイボリーW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アッシュグリーン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アッシュグリーン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アトランブルー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アトランブルー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アルトブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アルトブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アルベロBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アルベロBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンティークＧ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンティークＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンティックBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンティックBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンバーBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンバーBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンバーBRT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンバーBRT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンバーオリーブ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンバーオリーブ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンバーベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンバーベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'イエローPB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンバーベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンバーベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウイニーブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウイニーブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウィンザーグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウィンザーグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウオームレッド', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウオームレッド', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウォールBRB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウォールBRB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウォールオレンジ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウォールホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウォールホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウッドオレンジ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウッドオレンジ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'エンボスグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'エンボスグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オーセントグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オーセントグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オータムホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オータムホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オールドブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オールドブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オターグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オフホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オフホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オリーブグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オリーブグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オレンジブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オレンジブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カーキＡT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カーキＡT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カーサブラック', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カーサブラック', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カーサホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カーサホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カームグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カームグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カキシブ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カキシブ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ガトーベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ガトーベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カメオグレージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カメオグレージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カラシイロ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カラシイロ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カリスベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カリスベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カリビアンY', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カリビアンY', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'キャメルベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'キャメルベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クールベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クールベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クラシックＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グランホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリアグリース', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリアグリース', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリアブランコ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリアブランコ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリーミーW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリーミーW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリームNO.２', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリームNO.２', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリームNO.３', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリームNO.３', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グリッシーBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グリッシーBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グリッドレッド', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グリッドレッド', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グリフェグリーン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL);

-- 301 ～ 400 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'グリフェグリーン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クレアールグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クレアールグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グレーＡ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グレーＡ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グレーＥNO.２', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グレーＥNO.２', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グレーＧR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グレーＧR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'コーラルオレンジ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'コーラルオレンジ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ココアBR NO.２', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ココアBR NO.２', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'コテヌリイエロー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'コテヌリソフトY', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'コテヌリソフトY', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'コテヌリホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'コテヌリホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'コラーレキャメル', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'コラーレキャメル', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'サポルベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'サポルベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'サンディＧ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'サンディＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'サンドオーカー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'サンドオーカー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'サンドベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'サンドベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シーダーオリーブ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シャドーＡT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シャドーＡT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シャローベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シャローベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シャンパンP', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シャンパンP', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シュクレクリーム', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シュクレクリーム', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ジュンセキBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ジュンセキBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ジョウセキＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シリアスキャメル', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シルキーP', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シルキーグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シルキーグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シルキーブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シルキーブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スウィートグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スウィートグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スウィートローズ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スウィートローズ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スクラッチC', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スクラッチC', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ステインＧ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ステインＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ステインK', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ステインK', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ステインT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ステインT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スノーホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スノーホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スパニッシュＡ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スパニッシュＡ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スモーキーBＬ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スモーキーBＬ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スレートグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スレートグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'セビリアンホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'セラベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'セラベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ソフトベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ソフトベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ソルベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ソルベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ダークグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ダークグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ダークグレーP', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ダークグレーP', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ダークブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ダークブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'タウングレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'タウングレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'タウンブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'チェリーSO', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'チェリーSO', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'チャコールグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'チャコールグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'チョコレートBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'チョコレートBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ツインブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ツインブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ティーフワイン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ティントローズ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ティントローズ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ティンバーＧ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ティンバーＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'デザートイエロー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'デザートイエロー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'デザートベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL);

-- 401 ～ 500 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'デザートベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'テラレッド', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'テラレッド', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'テラレッドNO.２', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'テラレッドNO.２', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'トヨタグリーン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'トヨタグリーン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'トリコロールR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'トリコロールR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'トルロオレンジ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'トルロオレンジ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ナチュラルBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ナチュラルBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ニューアイボリー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ニューアイボリー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ニューブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ニューブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルオーカー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルオーカー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'バーゼプラチナ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'バーゼプラチナ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'バーゼホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'バーゼホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ハーベストY', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ハーベストY', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'パールグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'パールグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'バウアーブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'バウアーブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'パセリグリーン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'パセリグリーン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ヒッコリーW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ヒッコリーW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブエノクリーム', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブエノクリーム', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'フォレストB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'フォレストB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンKS', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンKS', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンNO.２', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンNO.２', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンS', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンS', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンSＥＭ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンSＥＭ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラック', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラック', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラッドレッド', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラッドレッド', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブリッツイエロー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブリッツイエロー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブリティッシュＧ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブリティッシュＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブルーS', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブルーS', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'プレシャスBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'プレシャスBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'フレンチベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'フレンチベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'フレンチホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'フレンチホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブレンドBK', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブレンドBK', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'フロストグレー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'フロストグレー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ベージュビスク', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ベージュピンク', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ペールブルー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ペールブルー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ペールブルーB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホソビキベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホソビキベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホソビキホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホソビキホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ボルドーレッド', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ボルドーレッド', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.２', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.２', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.３', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.３', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.４', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.５', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.５', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトP', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトP', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトS', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ボワブラックB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ボワブラックB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'マーズブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL);

-- 501 ～ 600 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'マーズブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'マイルドBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'マイルドBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'マイルドパイン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'マイルドパイン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーピンク', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーピンク', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーブルーS', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーブルーS', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ムーンベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ムーンベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'モイスチャーBR', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'モイスチャーBR', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'モカＡT', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'モカＡT', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'モクメダークB', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'モクメダークB', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ユーロオレンジ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ユーロオレンジ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ユーロホワイト', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ユーロホワイト', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ライトキャメル', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ライトブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ライトブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ライトベージュ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ライトベージュ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ライトマスタード', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ライトマスタード', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ライトマルーン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ライトマルーン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ラスティーＧ', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ラスティーＧ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ラフィネシトラス', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ラフィネシトラス', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ランドブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ランドブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'リフレインW', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'リフレインW', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'レモードCC', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'レモードCC', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'レモードブルー', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'レモードブルー', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'レモードレッド', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'レモードレッド', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ロクショウ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ワインレッド', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ワインレッド', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ワサビグリーン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ワサビグリーン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウッドブラウン', 'S７０(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウッドブラウン', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アルミ', 'S７０(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ASSブルー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ASSブルー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Cライトグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Cライトグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Dクリーム', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Dクリーム', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Fイエロー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Fイエロー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Fキャメル', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Fキャメル', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Fブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Fブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Fホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Fホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Jオーカー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Jオーカー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Kオーカー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Kオーカー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Kモザイクグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Kモザイクグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Nクリーム', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Nクリーム', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Nセピア', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Nセピア', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Nダークブルー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Nダークブルー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Nホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Nホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Pチタングレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Pチタングレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'SPフォーンBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'SPフォーンBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'SSブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'SSブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'SカスタードBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'SカスタードBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TアイボリーDT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TアイボリーDT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TアイボリーEF', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TアイボリーEF', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TアスールO', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TアスールO', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tアルモブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tアルモブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TアンティークB', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TアンティークB', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL);

-- 601 ～ 700 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'TイエローDT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TイエローDT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TイエローSDT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TイエローSDT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tウグイスチャ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tウグイスチャ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TエスペリオW', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TエスペリオW', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TオレンジK', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TオレンジK', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TオレンジSDT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TオレンジSDT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TカジュアルＡ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TカジュアルＡ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tカロスミント', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tカロスミント', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TカンザスDB', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TカンザスDB', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TカンザスW', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TカンザスW', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TキールO', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TキールO', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TキールS', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TキールS', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TグリーンＧDT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TグリーンＧDT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TグレーPM', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TグレーPM', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tクレマベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tクレマベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tコールブラック', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tコールブラック', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tスギノキ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TステインB', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TステインB', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tセラベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tセラベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TソフトDT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TソフトDT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tソルアイボリー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tソルアイボリー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TチャコールBK', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TチャコールBK', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tテンダーブルー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tテンダーブルー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TネビアB', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TネビアB', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TパーチェF', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TパーチェF', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tパーチェカフェ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tパーチェカフェ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TパープルＧDT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TパープルＧDT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TハウッドS', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TハウッドS', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TヒウチY', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TヒウチY', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TピンクODT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TピンクODT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TファータF', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TファータF', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TファータK', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TファータK', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tファータバニラ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tファータバニラ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tフォンセワイン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tフォンセワイン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンK', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンK', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンKC', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TブラウンKC', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TブリックK', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TブリックK', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TフロストW', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TフロストW', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tベンガラ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tベンガラ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトDT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトDT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトEF', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトEF', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトV', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TホワイトV', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TモクメW', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TモクメW', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオBＧ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオBＧ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオW', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TモントリオW', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TリベルピュアW', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TリベルピュアW', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tルーツホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tルーツホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tルーツミスト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Tルーツミスト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TルーラルB', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TルーラルB', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tルナホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL);

-- 701 ～ 800 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'Tルナホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'TレジェC', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'TレジェC', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Tロクショウ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'Yスパニッシュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'Yスパニッシュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アースブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アースブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アイアンブラック', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アイアンブラック', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アイボリーW', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アイボリーW', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アッシュグリーン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アッシュグリーン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アトランブルー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アトランブルー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アルトブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アルトブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アルベロBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アルベロBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンティークＧ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンティークＧ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンティックBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンティックBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンバーBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンバーBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンバーBRT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンバーBRT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンバーオリーブ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンバーオリーブ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'アンバーベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'アンバーベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウイニーCC', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウイニーCC', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウイニーブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウイニーブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウィンザーグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウィンザーグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウオームレッド', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウオームレッド', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウォールBRB', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウォールBRB', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウォールホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウォールホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウッドオレンジ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウッドオレンジ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'エンボスグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'エンボスグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オーセントグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オーセントグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オータムホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オータムホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オールドブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オールドブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オフホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オフホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オリーブグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オリーブグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'オレンジブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'オレンジブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カーキＡT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カーキＡT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カーサブラック', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カーサブラック', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カーサホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カーサホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カームグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カームグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カキシブ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カキシブ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ガトーベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ガトーベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カラシイロ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カラシイロ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'カリスベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'カリスベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'キャメルベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'キャメルベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クールベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クールベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリアグリース', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリアグリース', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリアブランコ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリアブランコ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリーミーW', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリーミーW', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリームNO.２', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリームNO.２', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クリームNO.３', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クリームNO.３', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グリッシーBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グリッシーBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グリッドレッド', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グリッドレッド', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'クレアールグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'クレアールグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'グレーＥNO.２', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グレーＥNO.２', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL);

-- 801 ～ 900 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'グレーＧR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'グレーＧR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'コーラルオレンジ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'コーラルオレンジ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ココアBRNO.２', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ココアBRNO.２', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'コテヌリソフトY', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'コテヌリソフトY', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'コテヌリホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'コテヌリホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'コラーレキャメル', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'コラーレキャメル', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'サーモンオレンジ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'サンディＧ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'サンディＧ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'サンドB', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'サンドオーカー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'サンドオーカー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'サンドベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'サンドベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シャンパンP', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シャンパンP', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シュクレクリーム', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シュクレクリーム', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ジュンセキBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ジュンセキBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シルキーグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シルキーグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'シルキーブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'シルキーブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ジンシャーレッド', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スウィートグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スウィートグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ステインＧ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ステインＧ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ステインK', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ステインK', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ステインT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ステインT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スノーホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スノーホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スパニッシュＡ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スパニッシュＡ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'スモーキーBＬ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'スモーキーBＬ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'セラベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'セラベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ソルベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ソルベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ダークブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ダークブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'チェリーSO', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'チェリーSO', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'チャコールグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'チャコールグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'チョコレートBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'チョコレートBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ティンバーＧ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ティンバーＧ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'デザートイエロー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'デザートイエロー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'デザートベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'デザートベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'テラレッド', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'テラレッド', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'テラレッドNO.２', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'テラレッドNO.２', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'トヨタグリーン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'トヨタグリーン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'トリコロールR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'トリコロールR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'トルロオレンジ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'トルロオレンジ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ナチュラルBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ナチュラルBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ニューアイボリー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ニューアイボリー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルB', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルB', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルオーカー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルオーカー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ノーブルベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'バーゼホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'バーゼホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'パールグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'パールグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'バウアーブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'バウアーブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'パセリグリーン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'パセリグリーン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ハニーイエロー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ヒッコリーW', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ヒッコリーW', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブエノクリーム', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブエノクリーム', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンKS', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンKS', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL);

-- 901 ～ 985 件目
INSERT INTO `ExcutionBudget`.`tmp_import_sunrise`
(`manufacturer`,
`productnumber`,
`product_name`,
`color`,
`case`,
`case_unit`,
`quantity`,
`quantity_unit`,
`standard_price`,
`length`)
VALUES
('サンライズ', 'ブラウンNO.２', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンNO.２', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンS', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンS', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンSＥＭ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラウンSＥＭ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラック', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラック', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブラッドレッド', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブラッドレッド', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブリッツイエロー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブリッツイエロー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブリティッシュＧ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブリティッシュＧ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブルーS', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブルーS', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'プレシャスBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'プレシャスBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ブレンドBK', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ブレンドBK', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'フロストグレー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'フロストグレー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ベージュビスク', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ベージュビスク', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ベージュピンク', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ベージュピンク', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ペールブルー', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ペールブルー', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホソビキベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホソビキベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホソビキホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホソビキホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.２', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.２', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.３', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.３', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.５', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ホワイトNO.５', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'マーズブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'マーズブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'マイルドBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'マイルドBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'マイルドパイン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'マイルドパイン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーブルーS', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーブルーS', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ミルキーベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ムーンベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ムーンベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'モイスチャーBR', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'モイスチャーBR', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'モカＡT', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'モカＡT', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'モクメダークB', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'モクメダークB', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ユーロオレンジ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ユーロオレンジ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ユーロホワイト', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ユーロホワイト', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ライトベージュ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ライトベージュ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ライトマスタード', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ライトマスタード', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ライトマルーン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ライトマルーン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ラスティーＧ', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ラスティーＧ', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ラフィネシトラス', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ラフィネシトラス', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ランドブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ランドブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'リードグリーン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'レモードCC', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'レモードCC', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'レモードレッド', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'レモードレッド', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ワインレッド', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ワインレッド', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ワサビグリーン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ワサビグリーン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL),
('サンライズ', 'ウッドブラウン', 'H１００(6L缶)', NULL, NULL, '缶', 1, NULL, 0, NULL),
('サンライズ', 'ウッドブラウン', 'H１００(カートリッジ320ml)', NULL, NULL, '本', 1, NULL, 0, NULL);

-- 一時テーブルの件数確認 → tmp_rows が 985 なら STEP 3 へ
SELECT COUNT(*) AS tmp_rows FROM `ExcutionBudget`.`tmp_import_sunrise`;


/* ============================================================================
   STEP 3 : 一時テーブル → 登録先へ INSERT
   ============================================================================ */
START TRANSACTION;

SELECT @target_table AS target_table;   -- 登録先が正しいか必ず目視確認する

SET @sql = CONCAT('INSERT INTO `ExcutionBudget`.`', @target_table, '` ',
                  '(`manufacturer`, `productnumber`, `product_name`, `color`, `case`, `case_unit`, `quantity`, `quantity_unit`, `standard_price`, `length`) ',
                  'SELECT `manufacturer`, `productnumber`, `product_name`, `color`, `case`, `case_unit`, `quantity`, `quantity_unit`, `standard_price`, `length` ',
                  'FROM `ExcutionBudget`.`tmp_import_sunrise` ORDER BY `id`');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;


/* ============================================================================
   STEP 4 : 登録結果を確認する
   ---------------------------------------------------------------------------
   → inserted_rows が 985 なら COMMIT
   → 違えば ROLLBACK
   ============================================================================ */
SET @sql = CONCAT('SELECT COUNT(*) AS inserted_rows, MIN(`id`) AS min_id, MAX(`id`) AS max_id ',
                  'FROM `ExcutionBudget`.`', @target_table, '` WHERE `manufacturer` = ?');
PREPARE stmt FROM @sql;
EXECUTE stmt USING @manufacturer;
DEALLOCATE PREPARE stmt;


/* ============================================================================
   確定（STEP 4 で件数が正しいことを確認してから実行）
   ============================================================================ */
-- COMMIT;
-- ROLLBACK;


/* ============================================================================
   STEP 5 : 後片付け（COMMIT / ROLLBACK の後に実行）
   ============================================================================ */
DROP TEMPORARY TABLE IF EXISTS `ExcutionBudget`.`tmp_import_sunrise`;
